### ISSUE TITLE
i don't see custom attributes 'color', 'brand', 'fabric' etc

### ISSUE THREAD

**Issue by userz58** [akeneo-labs/custom-entity-demo#5]
please add example attribute_types.yml for entity Color ( http://docs.akeneo.com/master/cookbook/custom_entity/creating_an_attribute_type.html#creating-the-attribute-type )

**Comment by damien-carcel** [comment]
Hi.

Try with the last code from master. It should work.
Remember to run "php composer.phar doctrine:schema:update --force" to be sure your database is up to date.

Regards,
Damien
